### ISSUE TITLE
Try EMBEDDED_IN_VM flag

### ISSUE THREAD

**Issue by jw3** [jw3/test-case-pigpio-jvm-crash#2]
Try out [pigpio PR #8](https://github.com/joan2937/pigpio/pull/8) as mentioned here https://github.com/joan2937/pigpio/issues/138#issuecomment-332678801https://github.com/joan2937/pigpio/issues/138#issuecomment-332678801

I've read that PR in the past, but dont recall if I tried it or not.  Dont know why it wouldnt have been tried, but there is a chance.

It was reported in the thread that if fixed the issue :crossed_fingers:

**Comment by maitredede** [comment]
I am proposing PR https://github.com/joan2937/pigpio/pull/164 for a long-term fix.

**Comment by jw3** [comment]
I like that.  Seems necessary to support users who get it packaged and dont want to rebuild.

I look forward to testing soon.

**Comment by jw3** [comment]
> Seems necessary to support users who get it packaged and dont want to rebuild.

But primarily would benefit library developers, as they can distribute without having to advise users to rebuild.

Awesome.

Shared my thoughts over there in support of your PR.

**Comment by jw3** [comment]
`EMBEDDED_IN_VM` is a great success :+1:
